version: '3.8'

services:
  web:
    build: ./
    command: python wsgi.py run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv/restaurantes.csv:/srv/restaurantes.csv
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - 5432:5432
    command: postgres -c "max_connections=200"
    restart: always


volumes:
  postgres_data: